every second:
	loop all players:
		set {%loop-player%.tabrank} to loop-player's prefix
		set {%loop-player%.tabname} to loop-player's display name
		set the loop-player's tab name to "%{%loop-player%.tabrank}%%{%loop-player%.tabname}%" 
		set tab list header of loop-player to "%nl%&f-------&6-------&f-------&6-------&f-------&6-------&f-------%nl%%nl%&6&lAchieved%nl%"
		set loop-player's tab list footer to "%nl% &7{mode} server%nl%%nl%&6&lSTORE: &8server.buycraft.net%nl%&6&lFORUMS: &8forums.server.net%nl%%nl%&f-------&6-------&f-------&6-------&f-------&6-------&f-------"